### ISSUE TITLE
Few questions regarding current implementation and DCI

### ISSUE THREAD

**Issue by andriytyurnikov** [cjbottaro/schizo#7]
@cjbottaro thanks for sharing schizo

DCI in ruby and rails is really young, and experimental, and it would be very nice if you will also share your thoughts/opinions about schizo and DCI .

What are the pros and cons or reasoning behind : 

1) roles being implemented via Schizo::Role, not usual Module or ActiveSupport::Concern 

2) data objects being implemeted via Schizo::Data, instead of plain objects (don't want to mess with core classes?)

3) current implementation of ClassBuilder and ObjectBuilder as classes, _dci_ instance variable and way it is used via DCI_INSTANCE_VARIABLE

4) any other topics you would like to cover

Thanks.

**Comment by manuelmeurer** [comment]
@cjbottaro Are you still working on this gem? Just reading up about DCI in Ruby and this gem seems really interesting but last commit was a year ago...

**Comment by cjbottaro** [comment]
Nope.  We stopped using DCI altogether at my work, so my interests shifted elsewhere.  This gem is a fun little experiment, but without battle testing in production, who knows how it will scale or what subtle bugs / gotchas will arise from this approach.

**Comment by cjbottaro** [comment]
@andriytyurnikov Wow, sorry... I didn't see your message.

1)  ActiveSupport::Concern or including a Module into a Class will affect _all_ subsequently instantiated objects of that class.  That's not what we want.  Consider ActiveRecord's associations, which are defined on a Class.  Given my understanding of DCI, there will be cases where we want a "user" record to have different associations from another "user" record.  If we define those associations on the User class, then they will be available to all "user" records.

2)  Yes.  It's less invasive to define #as on Object or whatever.  It seems better to let the user pick and choose which classes to use DCI/Schizo with.

3)  Not really sure.  In general, I don't like to "pollute namespaces".  Rather than define a bunch of instance variables / methods on an object, I like to encapsulate all the functionality in a single place, in this case, the "dci" instance variable, kind of like the delgator pattern, I guess.  The constant DCI_INSTANCE_VARIABLE just allows for changing the name of the "dci" instance variable incase it conflicts with an existing instance variable named "dci".

4)  The key thing to understand in Schizo is what / why / how it solves the problem that it does.  The what / why is essentially this...

``` ruby
user1 = User.find(...)
user2 = User.find(...)
user1.extend(Poster)
user2.extend(Commenter)
user1.posts
user2.comments
user1.comments # *should* raise an error because user1 is not a commenter.
user2.posts # *should* raise an error because user2 is not a poster.
```

How can you accomplish that by including Modules or ActiveSupport#Concern?

**Comment by manuelmeurer** [comment]
I'm still learning about DCI in Ruby, but as far as I understood, the roles should just add _behavior_ to the objects (Interaction), and rudimentary methods and the data structure itself can (and should) be implemented on the models (Data).
Wouldn't the relation between users and posts/comments in this case be part of the data structure and thus be implemented in the class itself? Adding a `belongs_to` or `has_many` through a Role doesn't really feel right...

**Comment by andriytyurnikov** [comment]
@manuelmeurer 
while I do share your concerns, and associations are usually part of data object class in my code, there is another point:
`belongs_to` or `has_many` are not necessary about **data structure**, but maybe about **data access**
this makes much more sense, when we have some kind of polymorphic association or NoSQL, though
